name: Build & Pack

on:
  push:
    branches: main
    #tags: "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    #- name: Set Version
    #  run: echo "VER=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    #- name: Show Version  
    #  run: echo ${VER}
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release --no-build --output .
